# Generated by Django 3.0.8 on 2020-08-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
                ('activityPeriods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ActivityPeriods')),
            ],
        ),
    ]
