# Generated by Django 3.0.8 on 2020-08-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200812_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='activityPeriods',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activityPeriod', to='home.ActivityPeriods'),
            preserve_default=False,
        ),
    ]
