# Generated by Django 3.0.8 on 2020-08-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_members_activityperiods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiods',
            name='members',
        ),
        migrations.AlterField(
            model_name='members',
            name='activityPeriods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ActivityPeriods'),
        ),
    ]
