# Generated by Django 3.0.8 on 2020-08-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200812_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='activityPeriods',
        ),
        migrations.AddField(
            model_name='activityperiods',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Members'),
            preserve_default=False,
        ),
    ]
