# Generated by Django 3.0.8 on 2020-08-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200812_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='home.Members'),
        ),
    ]
