# Generated by Django 3.0.8 on 2020-08-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200812_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiods',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='activityperiods',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='home.Members'),
        ),
    ]
